
name: docker build

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Get image tag
      id: tags
      run: echo "::set-output name=tag::$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build Test
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        build-args: |
          DRIVER_VERSION=450.102.04
        tags: |
          rdbox/${{ env.CI_REPOSITORY_NAME }}:${{ steps.tags.outputs.tag }}
          rdbox/${{ env.CI_REPOSITORY_NAME }}:latest